FROM node:22.15.0-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY src/ ./src/
COPY tsconfig.json .sequelizerc ./
RUN npm run build-ts

# ---
FROM node:22.15.0-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist/ ./dist/
COPY --from=build /app/.sequelizerc ./
COPY docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh

EXPOSE 10020

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["web"]
